Migrate to Circle CI v2
Our setup doesn't seem to be working with JDK 9 yet (fails with `Fatal error compiling: java.lang.NoClassDefFoundError: javax/annotation/Generated: javax.annotation.Generated`). Leaving it out for now, since the old setup only used JDK 8.

Circle doesn't support wildcard checksums very well, and since we have multiple `pom.xml` files, I've skipped caching dependencies for now.